name: CloudLab Windows Panel

on:
  workflow_dispatch:

jobs:
  winlab:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:

    - name: Show System Info
      run: |
        echo ===== IP INFO =====
        ipconfig
        echo ===== PORTS =====
        netstat -ano

    - name: Download Tailscale
      run: |
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale.exe

    - name: Install Tailscale
      run: |
        Start-Process .\tailscale.exe -ArgumentList "/S" -Wait

    - name: Start Tailscale
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey ${{ secrets.TS_AUTHKEY }} --accept-routes

    - name: Show Tailscale IP
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" ip

    - name: Show RDP Port
      run: |
        netstat -ano | findstr 3389

    - name: Keep Runner Alive
      run: |
        ping -t 127.0.0.1
