name: Ultimate-CloudLab-RDP

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  cloudlab:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:

    - name: Create User
      run: |
        net user deva rise123 /add
        net localgroup Administrators deva /add

    - name: Enable Remote Desktop
      run: |
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Show Network Info
      run: |
        echo ===== IP INFO =====
        ipconfig
        echo ===== PORTS =====
        netstat -ano

    - name: Install Tailscale
      run: |
        curl -fsSL https://pkgs.tailscale.com/stable/tailscale-setup.exe -o tailscale.exe
        Start-Process .\tailscale.exe -ArgumentList "/S" -Wait

    - name: Start Tailscale
      run: |
        Start-Service Tailscale
        Start-Sleep -Seconds 5

    - name: Connect Tailscale
      run: |
        tailscale up --authkey=${{ secrets.TSKEY_AUTH }} --hostname=cloud-lab-rdp

    - name: Keep Server Alive
      run: |
        for ($i=1; $i -le 360; $i++) {
          Write-Output "CloudLab Running Minute $i"
          Get-Date
          Start-Sleep -Seconds 60
        }

    - name: Auto Restart Workflow
      run: |
        curl -X POST `
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" `
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/rdp.yml/dispatches `
        -d '{"ref":"main"}'
